name: Post welcome comment
on:
  workflow_dispatch:
permissions:
  pull-requests: write
jobs:
  job_1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 1" && sleep 5 && echo "end 1"
  job_2:
    name: Job 2
    needs: Job_1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 2" && sleep 5 && echo "end 2"
  job_3:
    name: Job 3
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 3" && sleep 5 && echo "end 3"
